# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 445  #https端口
  servlet:
    context-path: /app-api
  http:  #http 端口
    port: 8083
  connection-timeout: 18000000
  ssl:
    key-store: classpath:www-ubfly-projks.jks
    key-store-password:
    key-store-type: JKS
    key-alias: 1
  #domain: a.jhdriver.org
  domain: 47.75.241.214
  #domain: 172.20.20.82

# mysql
spring:
  # 环境 dev|main|prod
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 200MB
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

renren:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭

config:
  jwt:
    secret: abcdefg1234567
    #token有效时长
    exprie: 3600
    #header名称
    header: token
  debug: false



#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cube.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'



